### ISSUE TITLE
Feature Request: Add command/MSBuild target to get the Unique ID of a .jar file

### ISSUE THREAD

**Issue by NightOwl888** [ikvm-revived/ikvm-maven#1]
We have some documentation that explains what the rules are for making a Unique ID from a .jar file (although I think the only place it exists now is [on Discord](https://discordapp.com/channels/973730543948673024/973730543948673027/992579395229323356)). However, for automation purposes, it would be useful to be able to hand a `.jar` to a command and get back the Unique ID that will be used, since the rules are a bit complex. Furthermore, it would be useful to obtain the Unique ID regardless of context:

1. On the command line
2. Inside of MSBuild
3. As a .NET API

Since the Unique ID can be used instead of a `.jar` file reference in `<IkvmReference>` (or at least that is what [I have been told](https://discordapp.com/channels/973730543948673024/973730543948673027/992776109584302101) by @wasabii), it would be useful to be able to predict what these Unique IDs are rather than guessing until you find it.

**Comment by wasabii** [comment]
That said... You asked about a unique jar ID.... So maybe you were talking about something else?

**Comment by NightOwl888** [comment]
Yes, I was referring to the `<IkvmReference>` which we now have some documentation for (in this issue). Maybe I am conflating the assembly naming logic with the unique id, which is why I created this issue. The file naming of the assemblies makes them difficult to dynamically refer to in the build (although it is probably less of an issue than I may have realized).

The example you provided makes working with these easier.

**Comment by wasabii** [comment]
Yeah. So, I guess reopen the issue over on `ikvm` but name it something else. The answer I provided is at least relevant to MavenReference, so can stay over here.
