### ISSUE TITLE
Is Classifier supported?

### ISSUE THREAD

**Issue by martin-honnen** [ikvm-revived/ikvm-maven#11]
I am trying to use e.g.

```
	  <MavenReference Include="xercesImpl">
		  <GroupId>org.exist-db.thirdparty.xerces</GroupId>
		  <ArtifactId>xercesImpl</ArtifactId>
		  <Classifier>xml-schema-1.1</Classifier>
		  <Version>2.12.2</Version>
	  </MavenReference>
```

but it seems the `Classifier` is not taken into account. Is that supposed to work or is it not supported?

**Comment by wasabii** [comment]
It is actually supported. Getting a particular error?

**Comment by martin-honnen** [comment]
Sorry, I kind of misinterpreted the error that no support for XSD 1.1 was found from some sample code as a failure of the Maven build process. But the DLL that is created has the right classes like e.g. `org.apache.xerces.jaxp.validation.XMLSchema11Factory` so it seems the error occurs at run time as a failure to detect/load those classes. I will need to look further into why that is not happening on the Java side but occurs with the equivalent C# code.

**Comment by wasabii** [comment]
Chances are it has to do with the class loader. If the code uses runtime reflection, or tries to load resources by name, it won't be able to find the appropriate assemblies if they're not yet loaded. But you can load them by hand.
