### ISSUE TITLE
MavenReference would generate "flywaydb" assembles with the same name.

### ISSUE THREAD

**Issue by craigskeat** [ikvm-revived/ikvm-maven#12]
The following MavenReferences would both generate assembles with the same name "org.flywaydb.core.dll",
And which comes first, which would overwrites others.

`<MavenReference Include="flyway-core">
	<GroupId>org.flywaydb</GroupId>
	<ArtifactId>flyway-core</ArtifactId>
	<Classifier></Classifier>
	<Version>9.2.0</Version>
</MavenReference>
<MavenReference Include="flyway-mysql">
	<GroupId>org.flywaydb</GroupId>
	<ArtifactId>flyway-mysql</ArtifactId>
	<Classifier></Classifier>
	<Version>9.2.0</Version>
</MavenReference>`

I don't know what to do now.

**Comment by wasabii** [comment]
It looks like `flyway-mysql.jar`'s MANIFEST.MF file includes `Automatic-Module-Name` of `org.flywaydb.core`. As such, MavenReference dutifully picks that as the assembly name.

Basically this is a bug in flyway-mysql. Automatic-Module-Names should be unique.

There is no real way to fix this in MavenReference. We have to pick something. And the something we pick has to be unique and stable. And the only thing that that meets those requirements is Automatic-Module-Name.

**Comment by wasabii** [comment]
Funny:

https://github.com/flyway/flyway/pull/3462

**Comment by craigskeat** [comment]
Thanks @wasabii.

I've tried IkvmReference as follows, and get flywaydb working. (Yes, I've cached jars in the Jar folder.)
`<IkvmReference Include="Jar/flyway-core-9.2.2.jar">
      <AssemblyName>flyway-core</AssemblyName>
      <AssemblyVersion>9.2.2.0</AssemblyVersion>
      <Compile>Jar/flyway-core-9.2.2.jar;Jar/flyway-mysql-9.2.2.jar;Jar/mariadb-java-client-3.0.7.jar</Compile>
    </IkvmReference>`

The MavenReference is so amazing to me, I'll always check back if I could switch back.

**Comment by wasabii** [comment]
It will still work with the workaround I mentioned.

You just can't publish any of this to nuget safely

**Comment by craigskeat** [comment]
I would try the workaround when I fully understand it.
Thanks for your reminder, I am not going to make any of Nuget packages. I think I know the consequences.

I know it's too dirty now to hard code too many version numbers and referencing too many jars in IkvmReference, at least for me.
I would love to switch back to MavenReference when I could handle it.
