### ISSUE TITLE
Can one use MavenReference but use a newer version of some dependency?

### ISSUE THREAD

**Issue by martin-honnen** [ikvm-revived/ikvm-maven#13]
I have a question about the use of `MavenReference`, when I use e.g. `<MavenReference Include="name.dmaus.schxslt:cli" Version="1.9.1"/>` I get that Java dependency nicely included and  all its subdependencies, which for instance, in the case of `name.dmaus.schxslt:cli` includes a rather old version (9.9.1.6) of `net.sf.saxon:Saxon-HE`.

In a Java IDE I am usually easily able to use a newer version of Saxon-HE (let says the latest 11.4) by adding e.g.

```
       <dependency>
            <groupId>net.sf.saxon</groupId>
            <artifactId>Saxon-HE</artifactId>
            <version>11.4</version>
        </dependency>
```

in my POM file and then the whole project (including `name.dmaus.schxslt:cli`) uses that latest version.

With IKVM Maven I have tried to add e.g. `<MavenReference Include="net.sf.saxon:Saxon-HE" Version="11.4"/>` but it looks like my code using e.g. `name.dmaus.schxslt.cli.Application` continues to compile/build and run against the 9.9.1.6 version of Saxon-HE.

Is there an easy/elegant way to ensure a newer/latest version of a subdependency is used?

I have only managed that by abandoning `MavenReference` and downloading all jars I need/want and manually constructing all `IkvmReference`s needed.

**Comment by wasabii** [comment]
It is supposed to work exactly as you described. Sounds like a bug.

**Comment by wasabii** [comment]
I built a simple unit test, and it actually does seem to be working correctly.

**Comment by wasabii** [comment]
Also, I created a very very simple csproj file, and it also works fine here:

```
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net6.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="IKVM.Maven.Sdk" Version="1.0.1" />
        <MavenReference Include="name.dmaus.schxslt:cli" Version="1.9.1"/>
        <MavenReference Include="net.sf.saxon:Saxon-HE" Version="11.4"/>
    </ItemGroup>

</Project>

```
The `Saxon.HE.dll` produced into bin/ is 11.4.

**Comment by martin-honnen** [comment]
Perhaps it is me failing to understand which assembly is used or loaded.
With your example adding e.g. `Program.cs` with

```
Console.WriteLine($"{Environment.Version} {Environment.OSVersion}");
name.dmaus.schxslt.cli.Application.main(args);
```

and then running it with command line arguments
```
-v
-d sample1.xml
-o sample1-schxslt191IKVMNet6.svrl
-s sample1.sch
```
where `sample1.xml` is e.g.
```
<?xml version="1.0" encoding="utf-8" ?>
<root>
	<item>abc</item>
	<item>a1c</item>
</root>

```
and `sample1.sch` is e.g.
```
<?xml version="1.0" encoding="utf-8" ?>
<schema xmlns="http://purl.oclc.org/dsdl/schematron" queryBinding="xslt3">
	<pattern>
		<rule context="item">
			<report test="matches(., '^\p{L}+$')">item contains only letters.</report>
		</rule>
	</pattern>
</schema>

```
the produced `.svrl` file says `<skos:prefLabel>SchXslt/1.9.1 SAXON/HE 9.9.1.6</skos:prefLabel>` while doing something on the Java side produces e.g. `<skos:prefLabel>SchXslt/1.9.1 SAXON/HE 11.4</skos:prefLabel>`.

So based on that it looks to me as if the .NET side pulls in and uses the old 9.9.1.6 version of Saxon-HE, at least when `name.dmaus.schxslt.cli.Application.main()` is run.

**Comment by wasabii** [comment]
Look at the actual assembly in the bin directory. Is it the correct version?

**Comment by martin-honnen** [comment]
It says 11.4.0.0 in the file properties, yes, but somehow that is not what seems to be running.

**Comment by wasabii** [comment]
So it looks like https://github.com/schxslt/schxslt has a POM variable for 'saxon.version', which sets the dependency. That's always going to be 9 since they built it with 9.

I can't quite find where in the code they output the version string. But my guess is going to be they don't interrogate the actual JAR for it, but just pass through the build variable. Can't find where they do that though.

**Comment by wasabii** [comment]
https://github.com/schxslt/schxslt/blob/master/core/src/main/resources/xslt/2.0/version.xsl seems to be where the version stirng is generated. They get the XSLT processor information from system-property(). I don't know enough about this to know how that is derived. Maybe from Saxon itself?

**Comment by martin-honnen** [comment]
Yes, the XSLT standard/language defines a `system-property` function and defines also some predefined property names and that is called e.g. `<xsl:value-of separator="/" select="(system-property('xsl:product-name'), system-property('xsl:product-version'))"/>`. Only for Saxon 11.4 it would not return `9.9.1.6`.

But looking at other generated assemblies I think I at least see where the number comes from, an assembly `cli.dll` contains some Schxslt classes and the whole Saxon classes, but the 9.9.1.6 ones.

**Comment by wasabii** [comment]
Yeah. The original JAR has them all. So this is a classloader difference probably.

Binding to assemblies takes place different in .NET, since there are assemblies. The references passed are searched in order for the type to bind to. So it's finding the classes in cli.dll (cli.jar) before the ones in Saxon.

My guess here is cli.jar isn't meant to be used from applications. It looks like a JAR file which combines all the other libraries together to make a single executable.

**Comment by martin-honnen** [comment]
I see. I will need to reconsider my approach, it appears. Will need some time to ponder, but I will come back to this issue/question.

**Comment by wasabii** [comment]
This `cli` package is kinda borked, imo. Like, first, it's a convivence JAR. Simply to make java -jar work, without having to specify -cp to all of the dependencies.

Except it's in Maven... a package manager by it's nature, which is intended to resolve dependencies on the fly for you.

And it EXPRESSES those dependencies, even though it includes them itself.

To me it sort of goes against the spirit of using a dependency manager in the first place.

Anyways, you can simply not use `cli`, which after all, seems intended for execution from the command line. Just add a Maven reference to the underlying libraries and call those instead.

**Comment by wasabii** [comment]
The POM file for `cli` uses https://maven.apache.org/plugins/maven-assembly-plugin/. Which does exactly what it says it does.

**Comment by wasabii** [comment]
Seems to not be a bug in MavenReference. Does exactly what it's supposed to.
