### ISSUE TITLE
Handle pom packaged maven artifacts

### ISSUE THREAD

**Issue by dave-b-code** [ikvm-revived/ikvm-maven#3]
Currently when using a maven reference to an artifact which contains only a pom, you get the following error:

`error IKVMSDK0005: The IkvmReference maven$some-random-package:1.0.0 has an invalid Compile item '..\some-random-folder\some-random-package-1.0.0.pom'. Can only include jar or class files.`

It would be great to either automatically handle this by detecting `<packaging>pom</packaging> `or to allow manually listing dependencies which do not have jars. This may require modifications in the main ikvm repo so feel free to move this issue if it is more appropriate there. Many thanks for the excellent library!

**Comment by wasabii** [comment]
Hmm. What's this POM supposed to do?

**Comment by dave-b-code** [comment]
Yeah exactly. The artifact which failed for me was  [com.yahoo.vespa:documentapi 8.12.48](https://search.maven.org/artifact/com.yahoo.vespa/documentapi/8.12.48/jar) which fails on meta package [com.yahoo.vespa:documentapi-dependencies 8.12.48](https://search.maven.org/artifact/com.yahoo.vespa/documentapi-dependencies/8.12.48/pom). Many thanks!

**Comment by wasabii** [comment]
Wanna try the latest prerelease?

**Comment by dave-b-code** [comment]
Hi, many thanks for sorting this out so quickly. Just ran the latest nupkg locally and it installed com.yahoo.vespa:documentapi without error. Only issue now is it doesn't seem to be generating any classes within the com.yahoo.vespa.documentapi namespace, but this is a different issue I'll look into further separately. Thanks again for this fantastic library and your help!
