### ISSUE TITLE
How to use MavenReference with .NET framework project?

### ISSUE THREAD

**Issue by martin-honnen** [ikvm-revived/ikvm-maven#31]
As far as I understand both IKVM as well as IKVM.Maven.Sdk are supposed to work with .NET Core and with .NET framework projects. However, I wonder, given that the documentation for IKVM.Maven only shows the use of `MavenReference` within a .NET Core project file, how can `MavenReference` be used successfully in the context of a .NET framework project file because when I put e.g.

```
  <ItemGroup>
	<PackageReference Include="IKVM.Maven.Sdk" Version="1.4.1" />
	<MavenReference Include="net.sf.saxon:Saxon-HE" Version="11.5" />
  </ItemGroup>
```

into a .NET framework `.csproj` file with root element of e.g. `<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">..</Project>` I only get errors like `error CS0246` (the type or namespace name "net" was not found) when trying to use e.g. `using net.sf.saxon.s9api;` and code like e.g. `var processor = new Processor(false);`.

So it seems the `MavenReference` has not been used.

**Comment by wasabii** [comment]
All IKVM utilities only support SDK-style MSBuild projects. This is hilighted in the README. Or should be.

**Comment by wasabii** [comment]
>To use, install the IKVM.Maven.Sdk package from NuGet, and add a <MavenReference /> element to your SDK-style project. Various Maven options are supported through item-metadata.
