### ISSUE TITLE
Not contain full class in the package

### ISSUE THREAD

**Issue by hung-hust-97** [ikvm-revived/ikvm-maven#4]
Hi teams! I'm using jmrtd maven 0.7.31 but it no contain PassportService class and more class. This is my setup:
	`<ItemGroup>
		<MavenReference Include="jmrtd">
			<GroupId>org.jmrtd</GroupId>
			<ArtifactId>jmrtd</ArtifactId>
			<Classifier></Classifier>
			<Version>0.7.31</Version>
		</MavenReference>
	</ItemGroup>`
This library i really need, please help

**Comment by wasabii** [comment]
You're probably going to have to do a bit more trouble shooting. Are you getting any errors or warnings during build? Have you checked the generated assembly?

**Comment by hung-hust-97** [comment]
i using config item group. It using maven project. After that, I use create PassportService, this is instane in JMRTD repo java, but in C# not found

**Comment by hung-hust-97** [comment]
![image](https://user-images.githubusercontent.com/32328578/178102515-36eaff67-d051-45d3-9776-6aad9dabbecb.png)
 package in the C# and package in the java below (all the class missing in red circle ):
 
![image](https://user-images.githubusercontent.com/32328578/178102570-8544d75e-55ef-468d-a7ba-5f22b7b28769.png)

**Comment by wasabii** [comment]
I don't know how those screenshots are supposed to help. The first doesn't list the classes in the namespace.

**Comment by hung-hust-97** [comment]
in the dependency in the Java, it have class PassportService, but after using in C# with ikvm then I don’t find this class

**Comment by wasabii** [comment]
The namespace is the first item in the list.,.......

**Comment by hung-hust-97** [comment]
the namespace is org.jmrtd

**Comment by wasabii** [comment]
Uh huh.

**Comment by hung-hust-97** [comment]
and i don’t tound PassportService class

**Comment by wasabii** [comment]
Look in the namespace.

**Comment by NightOwl888** [comment]
I put together a demo, and can confirm that the `org.jmrtd.PassportService` class is visible. I am using Visual Studio 2022, version 17.2.2.

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <RootNamespace>ikvm_maven_4</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <MavenReference Include="jmrtd">
      <GroupId>org.jmrtd</GroupId>
      <ArtifactId>jmrtd</ArtifactId>
      <Classifier></Classifier>
      <Version>0.7.31</Version>
    </MavenReference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="IKVM.Maven.Sdk" Version="1.0.0" />
  </ItemGroup>
</Project>
```

![image](https://user-images.githubusercontent.com/1538288/178111121-d81a0881-3821-4351-bff8-3bc3d4154849.png)

**Comment by hung-hust-97** [comment]
Thanks very much, I change the version dotnet to 3.1 and project is class library then it contain class PassportService. I will test them.

**Comment by hung-hust-97** [comment]
I have the new Problem, i adding the class jmrtd and scuba `	<ItemGroup>
		<MavenReference Include="jmrtd">
			<GroupId>org.jmrtd</GroupId>
			<ArtifactId>jmrtd</ArtifactId>
			<Classifier></Classifier>
			<Version>0.7.31</Version>
		</MavenReference>
	</ItemGroup>
	<ItemGroup>
		<MavenReference Include="scuba">
			<GroupId>net.sf.scuba</GroupId>
			<ArtifactId>scuba-sc-j2se</ArtifactId>
			<Classifier></Classifier>
			<Version>0.0.18</Version>
		</MavenReference>
	</ItemGroup>`
Scuba library use to connect with SmartCard. I don't know if the difference between smartcard calling protocol in C# and java is different but the result I get is empty array as shown below.
![image](https://user-images.githubusercontent.com/32328578/178133170-8c859f2f-838b-417e-84f3-36845740efcf.png)
![image](https://user-images.githubusercontent.com/32328578/178133178-5623a36a-3f2a-41ef-93d3-ad26ef55b71f.png)

**Comment by wasabii** [comment]
IKVM does not support javax.smartcardio

**Comment by hung-hust-97** [comment]
what a pity, it was all i needed, thank you 😢
