### ISSUE TITLE
Runtime exceptions when using MavenReference vs using IkvmReference

### ISSUE THREAD

**Issue by The-MAZZTer** [ikvm-revived/ikvm-maven#6]
Don't have super detailed details since I was doing this for work and didn't take notes as I figured it out, sorry. This should be enough to reproduce.

Basically including Tika like this doesn't work even though it should:

```
<MavenReference Include="org.apache.tika:tika-app" Version="2.4.1" />
```

(Side note: I picked tika-app since I was previously shelling out to the tika.,jar CLI in my app so I knew it had all the various plugins and such I would want included.)

If I use MavenReference, it seems to work OK until I actually go to call `TikaConfig.getDefaultConfig()`. When I do it throws a NoClassDefException that it can't find org.slf4j.LoggerFactory. But, that class is defined by IKVM's translation.

If I put a dummy call to `org.slf4j.LoggerFactory.getILoggerFactory()` before my TikaConfig call to force the class to be loaded, the error disappears.

But then I get a NoModuleFoundException for something internal to Tika while it's trying to find Detectors which is where I hit a dead end. I don't think I can do much about that and it's clear something is broken with IKVM at this point.

When I switched out the MavenReference for the precompiled tika app jar provided by Apache:

```
<IkvmReference Include="..\Path\To\tika.jar">
    <AssemblyVersion>2.4.1.0</AssemblyVersion>
</IkvmReference>
```

I can remove my dummy call and Tika runs fine. But I would expect this to be equivalent in behavior to the MavenReference.

One important note is that I am running on .NET Core 3.1. Haven't migrated to .NET 6 yet. Not sure if this would make a difference. Still supported for a few more months by Microsoft though.

**Comment by NightOwl888** [comment]
Offhand, I would say that since this is due to logging, it is most likely exactly the same problem and solution as https://github.com/ikvm-revived/ikvm/issues/169.

**Comment by The-MAZZTer** [comment]
The thing is the class it claims is missing is present which doesn't sound like the linked issue. But I will try it when I get back to this issue.

**Comment by wasabii** [comment]
@The-MAZZTer  Did you ever get this resolved in a later version? My suspicion is that it should have gone away with the defaulting of the class loader to assembly, which we did a few months ago.

If not, please reopen.

**Comment by The-MAZZTer** [comment]
I actually tried it today (was troubleshooting an issue with Tika after updating to .,NET 6 and latest IKVM (8.4.4) turned out to be an exception I could just ignore) and am having MSBuild compile time errors now, many messages complaining about duplicate types in different libraries (for tika-app). Those errors go away when using IkvmReference instead.

So I can't test runtime since compile time is broken now! :(

Also had another weird issue where 8.4.x nupkg wouldn't download from any site (download would hang unless I paused and later resumed it, which you can't do in nuget clients of course) but I traced it to the particular PC I am using, so I am guessing it is security software not liking IKVM or Java code.

**Comment by The-MAZZTer** [comment]
I looked into just including the individual components by checking the dependencies on maven but I'm not sure where to start there, they carved it up pretty good.

Just pulling in tika-app is simpler and seems to work fine when I reference the JAR directly.

Anyway I am doing this for work and got other stuff to do, it's working so I don't think I should spend any more time on it.
