### ISSUE TITLE
Adding/removing MavenReferences without doing a Clean Build causes build errors

### ISSUE THREAD

**Issue by The-MAZZTer** [ikvm-revived/ikvm-maven#7]
I get an error from IKVM.Maven.SDK (sorry forget the specific error, might have been a NullReferenceException) when I add a new MavenReference to a project that already has one and try to run, or remove a reference from a project that has two and then run.

I was specifically trying to diagnose my other issue with Tika I reported, by adding a reference to this: https://mvnrepository.com/artifact/org.slf4j/slf4j-log4j12/1.7.36

Doing so to my project which already had a reference to Tika and had previously built successfully then fails with an error.

Again sorry I can't provide more details, was doing stuff for work and had to prioritize getting it working over taking bug report notes.

**Comment by wasabii** [comment]
Not enough information to reproduce.
