### ISSUE TITLE
Tutorial?

### ISSUE THREAD

**Issue by GeorgeS2019** [ikvm-revived/ikvm-maven#8]
Curious about how to make it works. 

Is there anyone creating youtube on how to use this?

**Comment by GeorgeS2019** [comment]
Found!
https://github.com/martin-honnen/CoffeeSacksIKVMTest4

**Comment by GeorgeS2019** [comment]
@wasabii

I am trying to create **voronoi-treemap-lib.dll**

How would I setup the `MavenReference  `configuration, as it is not from Marven.
 Refers the [source](https://github.com/qbicsoftware-archive/voronoi-treemap-cli/blob/development/pom.xml)

```js

<MavenReference Include="life.qbic:voronoi-treemap-lib" Version="0.2" />
```
```js
      <dependency>
            <groupId>life.qbic</groupId>
            <artifactId>voronoi-treemap-lib</artifactId>
            <version>0.2</version>
        </dependency>
```

**Comment by GeorgeS2019** [comment]
Is this the way to proceed?

**voronoi-treemap-lib.jar**

```
<ItemGroup>
    <MavenReference Include="voronoi-treemap-lib">
      <GroupId>life.qbic</GroupId>
      <ArtifactId>voronoi-treemap-lib</ArtifactId>
      <Classifier></Classifier>
      <Version>0.2</Version>
    </MavenReference>
</ItemGroup>
```

**Comment by GeorgeS2019** [comment]
```
<IkvmReference Include="..\Path\To\voronoi-treemap-lib.jar">
    <AssemblyVersion>0.2</AssemblyVersion>
</IkvmReference>
```

**Comment by wasabii** [comment]
> @wasabii
> 
> I am trying to create **voronoi-treemap-lib.dll**
> 
> How would I setup the `MavenReference `configuration, as it is not from Marven. Refers the [source](https://github.com/qbicsoftware-archive/voronoi-treemap-cli/blob/development/pom.xml)
> 
> ```js
> <MavenReference Include="life.qbic:voronoi-treemap-lib" Version="0.2" />
> ```
> 
> ```js
>       <dependency>
>             <groupId>life.qbic</groupId>
>             <artifactId>voronoi-treemap-lib</artifactId>
>             <version>0.2</version>
>         </dependency>
> ```

You wouldn't. That's like asking how you would use nuget if there was no nuget package.

**Comment by GeorgeS2019** [comment]
Another relevant [example](https://github.com/NightOwl888/MavenReferencePoC):  **MavenReferencePoC**
