### ISSUE TITLE
Unrecognized Windows Sockets error: 11: connect

### ISSUE THREAD

**Issue by craigskeat** [ikvm-revived/ikvm-maven#9]
I've got,
`.nuget/packages/ikvm.maven.sdk/1.0.1/buildTransitive/netstandard2.0/IKVM.Maven.Sdk.targets(93,9): error : ArtifactTransferException: Could not transfer artifact (mvn_package:pom:version) from/to central (https://repo1.maven.org/maven2/): Unrecognized Windows Sockets error: 11: connect [(path_to_csproject)]`
in docker container debian:bullseye-20220801-slim.
And everything works fine on Windows 10/11.

**Comment by wasabii** [comment]
This is blocked on IKVM issue 89.

**Comment by GeorgeS2019** [comment]
[Issue 89: Socket Redesign for Linux](https://github.com/ikvm-revived/ikvm/issues/89)

**Comment by wasabii** [comment]
Should be solved in 1.2, which depends on IKVM 8.4.
